[2023-12-11T03:20:43.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Healthcare_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-11T03:20:43.490+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Healthcare_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-11T03:20:43.491+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-11T03:20:43.496+0000] {taskinstance.py:1382} INFO - Executing <Task(SubDagOperator): insert_fk_into_fact_table> on 2023-12-01 00:00:00+00:00
[2023-12-11T03:20:43.499+0000] {standard_task_runner.py:57} INFO - Started process 487 to run task
[2023-12-11T03:20:43.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Healthcare_Insurance-v01', 'insert_fk_into_fact_table', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/Healthcare_Insurance.py', '--cfg-path', '/tmp/tmpb4j2844m']
[2023-12-11T03:20:43.502+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask insert_fk_into_fact_table
[2023-12-11T03:20:43.531+0000] {task_command.py:416} INFO - Running <TaskInstance: Healthcare_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [running]> on host 88d78b0e9c67
[2023-12-11T03:20:43.569+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Healthcare_Insurance-v01' AIRFLOW_CTX_TASK_ID='insert_fk_into_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-11T03:20:43.572+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-11T03:20:43.589+0000] {subdag.py:172} INFO - Created DagRun: scheduled__2023-12-01T00:00:00+00:00
[2023-12-11T03:21:43.654+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-12-11T03:21:43.665+0000] {subdag.py:187} INFO - Execution finished. State is success
[2023-12-11T03:21:43.674+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Healthcare_Insurance-v01, task_id=insert_fk_into_fact_table, execution_date=20231201T000000, start_date=20231211T032043, end_date=20231211T032143
[2023-12-11T03:21:43.728+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-11T03:21:43.749+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
