[2023-12-12T21:28:26.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: home_insurance_ds-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_P1_POLICY_REFUSED scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-12T21:28:26.029+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: home_insurance_ds-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_P1_POLICY_REFUSED scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-12T21:28:26.029+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-12T21:28:26.058+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_fk_col_in_fact_table_P1_POLICY_REFUSED> on 2023-12-01 00:00:00+00:00
[2023-12-12T21:28:26.077+0000] {standard_task_runner.py:57} INFO - Started process 2171 to run task
[2023-12-12T21:28:26.081+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'home_insurance_ds-v01.insert_fk_into_fact_table', 'insert_fk_col_in_fact_table_P1_POLICY_REFUSED', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/home_insurance_dataset.py', '--cfg-path', '/tmp/tmpoac3xydr']
[2023-12-12T21:28:26.091+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask insert_fk_col_in_fact_table_P1_POLICY_REFUSED
[2023-12-12T21:28:26.190+0000] {task_command.py:416} INFO - Running <TaskInstance: home_insurance_ds-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_P1_POLICY_REFUSED scheduled__2023-12-01T00:00:00+00:00 [running]> on host 7a94ca99eac6
[2023-12-12T21:28:26.356+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='home_insurance_ds-v01.insert_fk_into_fact_table' AIRFLOW_CTX_TASK_ID='insert_fk_col_in_fact_table_P1_POLICY_REFUSED' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-12T21:28:26.361+0000] {sql.py:274} INFO - Executing: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE home_insurance_ds_pipeline
ADD COLUMN P1_POLICY_REFUSED_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE home_insurance_ds_pipeline
SET P1_POLICY_REFUSED_id = dimension_table_P1_POLICY_REFUSED.id
FROM dimension_table_P1_POLICY_REFUSED
WHERE COALESCE(home_insurance_ds_pipeline.P1_POLICY_REFUSED::text, '') = COALESCE(dimension_table_P1_POLICY_REFUSED.P1_POLICY_REFUSED::text, '');
[2023-12-12T21:28:26.382+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T21:28:26.404+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-12T21:28:26.417+0000] {sql.py:418} INFO - Running statement: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE home_insurance_ds_pipeline
ADD COLUMN P1_POLICY_REFUSED_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE home_insurance_ds_pipeline
SET P1_POLICY_REFUSED_id = dimension_table_P1_POLICY_REFUSED.id
FROM dimension_table_P1_POLICY_REFUSED
WHERE COALESCE(home_insurance_ds_pipeline.P1_POLICY_REFUSED::text, '') = COALESCE(dimension_table_P1_POLICY_REFUSED.P1_POLICY_REFUSED::text, '');, parameters: None
[2023-12-12T21:28:35.897+0000] {sql.py:427} INFO - Rows affected: 183073
[2023-12-12T21:28:35.932+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=home_insurance_ds-v01.insert_fk_into_fact_table, task_id=insert_fk_col_in_fact_table_P1_POLICY_REFUSED, execution_date=20231201T000000, start_date=20231212T212826, end_date=20231212T212835
[2023-12-12T21:28:35.980+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-12T21:28:36.003+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
