[2023-12-21T16:55:00.047+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_DifficultyConcentrating_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:55:00.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_DifficultyConcentrating_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:55:00.057+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-12-21T16:55:00.071+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): impute_DifficultyConcentrating_with_mode> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:55:00.075+0000] {standard_task_runner.py:57} INFO - Started process 1191 to run task
[2023-12-21T16:55:00.078+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings', 'impute_DifficultyConcentrating_with_mode', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/Indicators_of_Heart_Disease_2022.py', '--cfg-path', '/tmp/tmppwlusb3z']
[2023-12-21T16:55:00.081+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask impute_DifficultyConcentrating_with_mode
[2023-12-21T16:55:00.139+0000] {task_command.py:416} INFO - Running <TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_DifficultyConcentrating_with_mode scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e01071a5eb3
[2023-12-21T16:55:00.199+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings' AIRFLOW_CTX_TASK_ID='impute_DifficultyConcentrating_with_mode' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:55:00.200+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET DifficultyConcentrating = (
    SELECT DifficultyConcentrating 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE DifficultyConcentrating IS NOT NULL
    GROUP BY DifficultyConcentrating
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE DifficultyConcentrating IS NULL;
[2023-12-21T16:55:00.216+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:55:00.226+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:55:00.239+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET DifficultyConcentrating = (
    SELECT DifficultyConcentrating 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE DifficultyConcentrating IS NOT NULL
    GROUP BY DifficultyConcentrating
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE DifficultyConcentrating IS NULL;, parameters: None
[2023-12-21T16:55:01.447+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 74265 waits for ShareLock on transaction 1141764; blocked by process 74266.
Process 74266 waits for ShareLock on transaction 1141765; blocked by process 74267.
Process 74267 waits for ShareLock on transaction 1141766; blocked by process 74270.
Process 74270 waits for ShareLock on transaction 1141769; blocked by process 74272.
Process 74272 waits for ShareLock on transaction 1141763; blocked by process 74265.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (20530,8) in relation "indicators_of_heart_disease_2022_pipe"

[2023-12-21T16:55:01.475+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings, task_id=impute_DifficultyConcentrating_with_mode, execution_date=20231201T000000, start_date=20231221T165500, end_date=20231221T165501
[2023-12-21T16:55:01.490+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task impute_DifficultyConcentrating_with_mode (deadlock detected
DETAIL:  Process 74265 waits for ShareLock on transaction 1141764; blocked by process 74266.
Process 74266 waits for ShareLock on transaction 1141765; blocked by process 74267.
Process 74267 waits for ShareLock on transaction 1141766; blocked by process 74270.
Process 74270 waits for ShareLock on transaction 1141769; blocked by process 74272.
Process 74272 waits for ShareLock on transaction 1141763; blocked by process 74265.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (20530,8) in relation "indicators_of_heart_disease_2022_pipe"
; 1191)
[2023-12-21T16:55:01.539+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:55:01.594+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
