[2023-12-21T16:55:04.866+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_FluVaxLast12_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:55:04.870+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_FluVaxLast12_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:55:04.870+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-12-21T16:55:04.876+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): impute_FluVaxLast12_with_mode> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:55:04.879+0000] {standard_task_runner.py:57} INFO - Started process 1212 to run task
[2023-12-21T16:55:04.881+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings', 'impute_FluVaxLast12_with_mode', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/Indicators_of_Heart_Disease_2022.py', '--cfg-path', '/tmp/tmp620u70d0']
[2023-12-21T16:55:04.882+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask impute_FluVaxLast12_with_mode
[2023-12-21T16:55:04.911+0000] {task_command.py:416} INFO - Running <TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_FluVaxLast12_with_mode scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e01071a5eb3
[2023-12-21T16:55:04.951+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings' AIRFLOW_CTX_TASK_ID='impute_FluVaxLast12_with_mode' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:55:04.951+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET FluVaxLast12 = (
    SELECT FluVaxLast12 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE FluVaxLast12 IS NOT NULL
    GROUP BY FluVaxLast12
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE FluVaxLast12 IS NULL;
[2023-12-21T16:55:04.957+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:55:04.962+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:55:04.966+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET FluVaxLast12 = (
    SELECT FluVaxLast12 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE FluVaxLast12 IS NOT NULL
    GROUP BY FluVaxLast12
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE FluVaxLast12 IS NULL;, parameters: None
[2023-12-21T16:55:07.745+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 74279 waits for ShareLock on transaction 1141768; blocked by process 74269.
Process 74269 waits for ShareLock on transaction 1141774; blocked by process 74279.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (24440,26) in relation "indicators_of_heart_disease_2022_pipe"

[2023-12-21T16:55:07.756+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings, task_id=impute_FluVaxLast12_with_mode, execution_date=20231201T000000, start_date=20231221T165504, end_date=20231221T165507
[2023-12-21T16:55:07.763+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task impute_FluVaxLast12_with_mode (deadlock detected
DETAIL:  Process 74279 waits for ShareLock on transaction 1141768; blocked by process 74269.
Process 74269 waits for ShareLock on transaction 1141774; blocked by process 74279.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (24440,26) in relation "indicators_of_heart_disease_2022_pipe"
; 1212)
[2023-12-21T16:55:07.803+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:55:07.833+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
