[2023-12-19T04:46:17.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Automobile_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T04:46:17.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Automobile_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T04:46:17.731+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-19T04:46:17.737+0000] {taskinstance.py:1382} INFO - Executing <Task(SubDagOperator): insert_fk_into_fact_table> on 2023-12-01 00:00:00+00:00
[2023-12-19T04:46:17.739+0000] {standard_task_runner.py:57} INFO - Started process 1240 to run task
[2023-12-19T04:46:17.742+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Automobile_Insurance-v01', 'insert_fk_into_fact_table', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/Automobile Insurance.py', '--cfg-path', '/tmp/tmpmor35op7']
[2023-12-19T04:46:17.743+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask insert_fk_into_fact_table
[2023-12-19T04:46:17.774+0000] {task_command.py:416} INFO - Running <TaskInstance: Automobile_Insurance-v01.insert_fk_into_fact_table scheduled__2023-12-01T00:00:00+00:00 [running]> on host 07f4bc2fb49b
[2023-12-19T04:46:17.813+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Automobile_Insurance-v01' AIRFLOW_CTX_TASK_ID='insert_fk_into_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-19T04:46:17.817+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-19T04:46:17.838+0000] {subdag.py:172} INFO - Created DagRun: scheduled__2023-12-01T00:00:00+00:00
[2023-12-19T04:47:17.880+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-12-19T04:47:17.898+0000] {subdag.py:187} INFO - Execution finished. State is success
[2023-12-19T04:47:17.912+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Automobile_Insurance-v01, task_id=insert_fk_into_fact_table, execution_date=20231201T000000, start_date=20231219T044617, end_date=20231219T044717
[2023-12-19T04:47:17.948+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-19T04:47:17.967+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
