[2023-12-21T16:15:12.357+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Insurance_Fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_PastNumberOfClaims scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:15:12.395+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Insurance_Fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_PastNumberOfClaims scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:15:12.405+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-21T16:15:12.435+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_fk_col_in_fact_table_PastNumberOfClaims> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:15:12.455+0000] {standard_task_runner.py:57} INFO - Started process 895 to run task
[2023-12-21T16:15:12.466+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Insurance_Fraud-v01.insert_fk_into_fact_table', 'insert_fk_col_in_fact_table_PastNumberOfClaims', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/Insurance_Fraud.py', '--cfg-path', '/tmp/tmp8man5nbc']
[2023-12-21T16:15:12.472+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask insert_fk_col_in_fact_table_PastNumberOfClaims
[2023-12-21T16:15:12.650+0000] {task_command.py:416} INFO - Running <TaskInstance: Insurance_Fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_PastNumberOfClaims scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e15cdf87c56
[2023-12-21T16:15:12.810+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Insurance_Fraud-v01.insert_fk_into_fact_table' AIRFLOW_CTX_TASK_ID='insert_fk_col_in_fact_table_PastNumberOfClaims' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:15:12.813+0000] {sql.py:274} INFO - Executing: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE insurance_fraud_pipeline
ADD COLUMN PastNumberOfClaims_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE insurance_fraud_pipeline
SET PastNumberOfClaims_id = dimension_table_PastNumberOfClaims.id
FROM dimension_table_PastNumberOfClaims
WHERE COALESCE(insurance_fraud_pipeline.PastNumberOfClaims::text, '') = COALESCE(dimension_table_PastNumberOfClaims.PastNumberOfClaims::text, '');
[2023-12-21T16:15:12.833+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:15:12.852+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:15:12.867+0000] {sql.py:418} INFO - Running statement: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE insurance_fraud_pipeline
ADD COLUMN PastNumberOfClaims_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE insurance_fraud_pipeline
SET PastNumberOfClaims_id = dimension_table_PastNumberOfClaims.id
FROM dimension_table_PastNumberOfClaims
WHERE COALESCE(insurance_fraud_pipeline.PastNumberOfClaims::text, '') = COALESCE(dimension_table_PastNumberOfClaims.PastNumberOfClaims::text, '');, parameters: None
[2023-12-21T16:15:13.263+0000] {sql.py:427} INFO - Rows affected: 14873
[2023-12-21T16:15:13.280+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Insurance_Fraud-v01.insert_fk_into_fact_table, task_id=insert_fk_col_in_fact_table_PastNumberOfClaims, execution_date=20231201T000000, start_date=20231221T161512, end_date=20231221T161513
[2023-12-21T16:15:13.304+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-21T16:15:13.328+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
