[2023-12-19T04:58:12.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes.remove_fancy_char_in_zip_codes.make_state_name_decimal scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T04:58:12.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes.remove_fancy_char_in_zip_codes.make_state_name_decimal scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T04:58:12.114+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-19T04:58:12.120+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): remove_fancy_char_in_zip_codes.make_state_name_decimal> on 2023-12-01 00:00:00+00:00
[2023-12-19T04:58:12.122+0000] {standard_task_runner.py:57} INFO - Started process 841 to run task
[2023-12-19T04:58:12.126+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes', 'remove_fancy_char_in_zip_codes.make_state_name_decimal', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/bank_and_cc_complaints.py', '--cfg-path', '/tmp/tmpv7xp2gcf']
[2023-12-19T04:58:12.127+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask remove_fancy_char_in_zip_codes.make_state_name_decimal
[2023-12-19T04:58:12.160+0000] {task_command.py:416} INFO - Running <TaskInstance: bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes.remove_fancy_char_in_zip_codes.make_state_name_decimal scheduled__2023-12-01T00:00:00+00:00 [running]> on host 2ee4b7dc3cc7
[2023-12-19T04:58:12.206+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes' AIRFLOW_CTX_TASK_ID='remove_fancy_char_in_zip_codes.make_state_name_decimal' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-19T04:58:12.207+0000] {sql.py:274} INFO - Executing: -- params: table_name, col_name_to_update, new_data_type

-- ALTER COLUMN in TABLE
ALTER TABLE ***_complaints
ALTER COLUMN state_name 
SET DATA TYPE INTEGER;
[2023-12-19T04:58:12.213+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T04:58:12.221+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T04:58:12.227+0000] {sql.py:418} INFO - Running statement: -- params: table_name, col_name_to_update, new_data_type

-- ALTER COLUMN in TABLE
ALTER TABLE ***_complaints
ALTER COLUMN state_name 
SET DATA TYPE INTEGER;, parameters: None
[2023-12-19T04:58:12.229+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "state_name" of relation "***_complaints" does not exist

[2023-12-19T04:58:12.235+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=bank_and_cc_complaints-v01.remove_fancy_char_in_zip_codes, task_id=remove_fancy_char_in_zip_codes.make_state_name_decimal, execution_date=20231201T000000, start_date=20231219T045812, end_date=20231219T045812
[2023-12-19T04:58:12.240+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task remove_fancy_char_in_zip_codes.make_state_name_decimal (column "state_name" of relation "***_complaints" does not exist
; 841)
[2023-12-19T04:58:12.258+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T04:58:12.274+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
