[2023-12-21T16:57:56.315+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers.impute_missing_values_in_PhysicalHealthDays_with_median scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:57:56.320+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers.impute_missing_values_in_PhysicalHealthDays_with_median scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:57:56.321+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-21T16:57:56.328+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): impute_missing_values_in_PhysicalHealthDays_with_median> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:57:56.332+0000] {standard_task_runner.py:57} INFO - Started process 1584 to run task
[2023-12-21T16:57:56.336+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers', 'impute_missing_values_in_PhysicalHealthDays_with_median', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/Indicators_of_Heart_Disease_2022.py', '--cfg-path', '/tmp/tmpg8jisth9']
[2023-12-21T16:57:56.339+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask impute_missing_values_in_PhysicalHealthDays_with_median
[2023-12-21T16:57:56.385+0000] {task_command.py:416} INFO - Running <TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers.impute_missing_values_in_PhysicalHealthDays_with_median scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e01071a5eb3
[2023-12-21T16:57:56.442+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers' AIRFLOW_CTX_TASK_ID='impute_missing_values_in_PhysicalHealthDays_with_median' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:57:56.443+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET PhysicalHealthDays = subquery.median_value
FROM (
    SELECT 
        PhysicalHealthDays,
        CASE 
            WHEN COUNT(*) % 2 = 1 THEN percentile_cont(0.5) WITHIN GROUP (ORDER BY PhysicalHealthDays::numeric) 
            ELSE AVG(CASE WHEN PhysicalHealthDays IS NOT NULL THEN PhysicalHealthDays END)
        END AS median_value
    FROM indicators_of_heart_disease_2022_pipe
    WHERE indicators_of_heart_disease_2022_pipe.PhysicalHealthDays IS NOT NULL
    GROUP BY indicators_of_heart_disease_2022_pipe.PhysicalHealthDays
) AS subquery
WHERE indicators_of_heart_disease_2022_pipe.PhysicalHealthDays IS NULL;
[2023-12-21T16:57:56.451+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:57:56.457+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:57:56.465+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET PhysicalHealthDays = subquery.median_value
FROM (
    SELECT 
        PhysicalHealthDays,
        CASE 
            WHEN COUNT(*) % 2 = 1 THEN percentile_cont(0.5) WITHIN GROUP (ORDER BY PhysicalHealthDays::numeric) 
            ELSE AVG(CASE WHEN PhysicalHealthDays IS NOT NULL THEN PhysicalHealthDays END)
        END AS median_value
    FROM indicators_of_heart_disease_2022_pipe
    WHERE indicators_of_heart_disease_2022_pipe.PhysicalHealthDays IS NOT NULL
    GROUP BY indicators_of_heart_disease_2022_pipe.PhysicalHealthDays
) AS subquery
WHERE indicators_of_heart_disease_2022_pipe.PhysicalHealthDays IS NULL;, parameters: None
[2023-12-21T16:57:57.720+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 74429 waits for ShareLock on transaction 1141793; blocked by process 74432.
Process 74432 waits for ShareLock on transaction 1141794; blocked by process 74429.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (17826,12) in relation "indicators_of_heart_disease_2022_pipe"

[2023-12-21T16:57:57.737+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Indicators_of_Heart_Disease_2022-v01.impute_missing_values_numbers, task_id=impute_missing_values_in_PhysicalHealthDays_with_median, execution_date=20231201T000000, start_date=20231221T165756, end_date=20231221T165757
[2023-12-21T16:57:57.749+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task impute_missing_values_in_PhysicalHealthDays_with_median (deadlock detected
DETAIL:  Process 74429 waits for ShareLock on transaction 1141793; blocked by process 74432.
Process 74432 waits for ShareLock on transaction 1141794; blocked by process 74429.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (17826,12) in relation "indicators_of_heart_disease_2022_pipe"
; 1584)
[2023-12-21T16:57:57.771+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:57:57.805+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
